-- MySQL Script generated by MySQL Workbench
-- 01/21/19 10:12:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TicketOffice
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TicketOffice
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ticketoffice` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `ticketoffice` ;

-- -----------------------------------------------------
-- WORK
-- Table `TicketOffice`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketoffice`.`client` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `surname` VARCHAR(20) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `registrationDate` DATE NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `address` VARCHAR(45) NULL,
  `email` VARCHAR(30) NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tocketoffice`.`blackList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketoffice`.`blackList` (
  `id_blackList` INT NOT NULL AUTO_INCREMENT,
  `id_client` INT NOT NULL,
  `date_of_addition` DATE NOT NULL,
  PRIMARY KEY (`id_blackList`),
  INDEX `fk_blackList_client1_idx` (`id_client` ASC),
  CONSTRAINT `fk_blackList_client1`
    FOREIGN KEY (`id_client`)
    REFERENCES `ticketoffice`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TicketOffice`.`route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketoffice`.`route` (
  `id_route` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_route`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TicketOffice`.`station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketOffice`.`station` (
  `id_station` INT NOT NULL AUTO_INCREMENT,
  `id_route` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,

  PRIMARY KEY (`id_station`),
  INDEX `fk_station_routeStation1_idx` (`id_route` ASC),
  CONSTRAINT `fk_station_routeStation1`
    FOREIGN KEY (`id_route`)
    REFERENCES `ticketOffice`.`route` (`id_route`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TicketOffice`.`order_`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketOffice`.`order_` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `id_client` INT NOT NULL,
  `address` VARCHAR(45) NULL,
  `order_date` DATE NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `fk_order__client1_idx` (`id_client` ASC),
  CONSTRAINT `fk_order__client1`
    FOREIGN KEY (`id_client`)
    REFERENCES `ticketOffice`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketoffice`.`order_has_station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketoffice`.`order_has_station` (
  `id_order` INT NOT NULL,
  `id_station` INT NOT NULL,
  `count` INT NOT NULL,
  INDEX `fk_order_has_station_station1_idx` (`id_station` ASC),
  PRIMARY KEY (`id_order`, `id_station`),
  INDEX `fk_order_has_station_order_1_idx` (`id_order` ASC),
  CONSTRAINT `fk_order_has_station_station1`
    FOREIGN KEY (`id_station`)
    REFERENCES `InternetShop`.`station` (`id_station`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_station_order_1`
    FOREIGN KEY (`id_order`)
    REFERENCES `InternetShop`.`order_` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- WORK
-- Table `TicketOffice`.`administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketoffice`.`administrator` (
  `id_administrator` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_administrator`))
ENGINE = InnoDB;
-- -----------------------------------------------------

INSERT INTO `administrator` (`login`,`password`) VALUES ('admin','admin');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
