package by.htp.ticketoffice.controller.web.command.manager.util;

public enum CommandName {
    AUTHORIZATION,
    REGISTRATION,
    ADD_NEW_ROUTE,
    ADD_NEW_STATION,
    SHOW_INFORMATION_ABOUT_STATION,
    EDIT_STATION,
    REMOVE_STATION,
    GO_ADD_STATION,
    GO_EDIT_STATION,
    ADD_TO_BLACKLIST,
    REMOVE_FROM_BLACKLIST,
    ORDER,
    CANCEL_ORDER,
    LOG_OUT,
    NO_SUCH_COMMAND,
    CHOOSE_LANGUAGE,
    SHOW_CORRECT_CLIENTS,
    SHOW_BLACKLIST,
    SHOW_ORDERS,
    GO_TO_ADMIN_PAGE;


}
